// soc.mac
// 
// include file for SoC-specific asm macros
//
// Copyright (c) 2015, 2016 Freescale Semiconductor, Inc. All rights reserved.
//

//-----------------------------------------------------------------------------

#ifndef _SOC_MAC
#define	_SOC_MAC

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------

#endif // _SOC_MAC
