#!/bin/bash 

VERSION=$(git describe --always --dirty --tags 2>/dev/null);
if [ "$VERSION" = "" ]; then
VERSION="'none'"
fi

printf "/dts-v1/;\n" > $1
printf "\n" >> $1
printf "/{\n" >> $1
printf "	description = \"PPA Firmware\";\n" >> $1
printf "	#address-cells = <1>;\n" >> $1
printf "	images {\n" >> $1
printf "		firmware@1 {\n" >> $1
printf "			description = \"PPA Firmware: Version %s\";\n" $VERSION >> $1
printf "			data = /incbin/(\"../obj/monitor.bin\");\n" >> $1
printf "			type = \"firmware\";\n" >> $1
printf "			arch = \"arm64\";\n" >> $1
printf "			compression = \"none\";\n" >> $1
printf "		};\n" >> $1
printf "	};\n" >> $1
printf "\n" >> $1
printf "	configurations {\n" >> $1
printf "		default = \"config@1\";\n" >> $1
printf "		config@1 {\n" >> $1
printf "			description = \"PPA Secure firmware\";\n" >> $1
printf "			firmware = \"firmware@1\";\n" >> $1
printf "		};\n" >> $1
printf "	};\n" >> $1
printf "};\n" >> $1
