#
# Makefile - build AArch64 PPA
#
# -----------------------------------------------------------------------------

PLAT_BUILD=1

ifeq ($(PLAT_BUILD), 1)
    # setup a path prefix so we can find the src files
    PRE_PATH=../
endif

# -----------------------------------------------------------------------------

# include the soc makefile
include ../Makefile

# -----------------------------------------------------------------------------

