// soc.mac
// 
// include file for SoC-specific asm macros
//
// Copyright (c) 2015, 2016 Freescale Semiconductor, Inc. All rights reserved.
//

//-----------------------------------------------------------------------------

#ifndef _SOC_MAC
#define	_SOC_MAC

//-----------------------------------------------------------------------------

 // generate a core mask msb
.macro CoreMaskMsb $p1, $p2
     // input:  $p1 = core mask lsb
     // output: $p1 = core mask msb
     // 0x8000_0000 >> (31 - leading_zeroes_lsb)
    clz  \$p2, \$p1
    mov  \$p1, #31
    sub  \$p1, \$p1, \$p2
    mov  \$p2, #0x80000000
    lsr  \$p1, \$p2, \$p1
.endm

//-----------------------------------------------------------------------------

 // Note: $p1 must be a 64-bit register
 // GICD base address returned in $p1
.macro Get_GICD_Base_Addr $p1
    adr   \$p1, _gic_base_addr
    ldr   \$p1, [\$p1]
.endm

//-----------------------------------------------------------------------------

 // Note: $p1 must be a 64-bit register
 // GICC base address returned in $p1
.macro Get_GICC_Base_Addr $p1
    adr   \$p1, _gic_base_addr
    ldr   \$p1, [\$p1, #8]
.endm

//-----------------------------------------------------------------------------

#endif // _SOC_MAC
